pipeline {
    agent any
    parameters {
        string(name: 'firstname', defaultValue: 'Monica', description: 'First Name')
        string(name: 'lastname', defaultValue: 'Bing', description: 'last name')
    }

    stages {
        //stage('Clone Repo') {
        //    steps {
        //        checkout scm
        //    }
        //}
        stage('Call Script') {
            steps {
                sh 'chmod +x runshellscript/script.sh'
                sh 'runshellscript/script.sh ${firstname} ${lastname}'
            }
        }
    }
}
